# Site settings
title: Arca Solutions Tutorials & Training
email: basecode@arcasolutions.com
description: Tutorial for Developers about Arca Products
baseurl: "http://arcasolutions.github.io"
url: "http://arcasolutions.github.io/"

author:
  name     : 'Arca Solutions'
  email    : basecode@arcasolutions.com
  url      : http://arcasolutions.com
  facebook : http://facebook.com/arcasolutions
  twitter  : http://twitter.com/arcasolutions

github: https://github.com/arcasolutions
disqus_shortname: "arcasolutions"
google_analytics: ""

paginate: 20
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
